### ISSUE TITLE
dependency on R >=4.0

### ISSUE THREAD

**Issue by andybeet** [dbosak01/logr#15]
I was wondering why this needs to be dependent on R >= 4.0.
Is there a reason this wouldn't run with R 3.6.x? Or is this a personal choice?
I don't see any dependencies that require this.

**Comment by dbosak01** [comment]
There is no built-in dependency.  But I had someone try using on 3.6 and they were getting errors.  I had them upgrade to 4.0, and the errors disappeared.  So I put the > 4.0 dependency on the next release.  I guess the real issue is I don't have a good mechanism set up yet for testing prior versions.  It's probably time to start doing that.  Let me work on it.  Thanks for the feedback.

**Comment by dbosak01** [comment]
Version 1.2.4 submitted to CRAN with support back to R version 3.4.  Tested with GitHub actions.
