### ISSUE TITLE
Hard cap on size of string in print functions

### ISSUE THREAD

**Issue by Tinco0** [dbosak01/logr#43]
Hi,

After seeing this bit of code in the write_windows and write_other functions, I've been wondering if there is a reason for this limit of 100 characters.

```
    if (all(class(x) == "character")) {
      if (length(x) == 1 && nchar(x) < 100) {
        
        # Print the string
        cat(x, "\n")
        
      } else {
        
        # Print the object
        withr::with_options(c("crayon.colors" = 1), { 
          print(x, ..., )
        })
        
      }
```

If not, could this limit perhaps be variable and set via passing an argument to the print functions?

Thanks in advance!

**Comment by dbosak01** [comment]
I think this was just so that for a short string it would print it directly instead of as a vector.  For the print function, it will print it as [1] "Hello" while for the cat it is just "Hello".  I was trying to distinguish between a simple message sent with put() or log_print() and an actual character vector that you are dumping to the log.  Either way, it will get logged.  Only difference is whether the "[1]" shows up in front or not.  

Is this actually causing you trouble?

**Comment by Tinco0** [comment]
I now understand your point to distinguish between the two options, and see that it makes sense.
It is not causing me trouble, it was just a thought that crossed my mind, since in my specific case I have very long messages that I wanted to send to the log but not in the print output format, but cat, since it escapes characters, while print does not.
I believe it is better to break my messages in smaller parts.

Thanks for the reply, though!!
Much appreciated

**Comment by dbosak01** [comment]
I see.  I'm willing to do something to accommodate long messages.  Let me think about it.  CRAN is closed for the next week anyway, so I can't send the updates that are waiting.

**Comment by dbosak01** [comment]
I made it so that long strings will be wrapped instead of going to print(). You can try it out:

devtools::install_github('https://github.com/dbosak01/logr')
